// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc9zzN8sD4GzgC_Y0lAo3Mk35DwihlJhk',
    appId: '1:876478177791:web:8a84cc1685e623c88ec7ca',
    messagingSenderId: '876478177791',
    projectId: 'jeropay-baa6f',
    authDomain: 'jeropay-baa6f.firebaseapp.com',
    storageBucket: 'jeropay-baa6f.firebasestorage.app',
    measurementId: 'G-GH1EHHE7K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVVXxwn94CvbR2qvGyDru1b7Bc2E7GCBo',
    appId: '1:876478177791:android:17acfd59f8328d458ec7ca',
    messagingSenderId: '876478177791',
    projectId: 'jeropay-baa6f',
    storageBucket: 'jeropay-baa6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7RsgP3-Vn9F64ibKDBnJtowL9eLczh7M',
    appId: '1:876478177791:ios:92519cfe253a9f908ec7ca',
    messagingSenderId: '876478177791',
    projectId: 'jeropay-baa6f',
    storageBucket: 'jeropay-baa6f.firebasestorage.app',
    iosBundleId: 'com.jeropay.ng.jeropay',
  );
}
